namespace WPFinalPlease
{
    partial class ucAccount
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucAccount));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.elipseAccount = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.txtSalary = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtExperience = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCMND = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtGender = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dtpBirthdate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.pnBirthdate = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblGender = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblName = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblBirthdate = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblCMND = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblAddress = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPhone = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblEmail = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblExperience = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblSalary = new Bunifu.UI.WinForms.BunifuLabel();
            this.drdCertificate = new Bunifu.UI.WinForms.BunifuDropdown();
            this.drdOccupation = new Bunifu.UI.WinForms.BunifuDropdown();
            this.pnCertificate = new Bunifu.UI.WinForms.BunifuPanel();
            this.pnOccupation = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblOccupation = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblCertificate = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblBio = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtBio = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnRegister = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnChangeInfo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pnCertificate.SuspendLayout();
            this.pnOccupation.SuspendLayout();
            this.pnRegister.SuspendLayout();
            this.SuspendLayout();
            // 
            // txtName
            // 
            this.txtName.AcceptsReturn = false;
            this.txtName.AcceptsTab = false;
            this.txtName.AnimationSpeed = 200;
            this.txtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtName.BackColor = System.Drawing.Color.Transparent;
            this.txtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtName.BackgroundImage")));
            this.txtName.BorderColorActive = System.Drawing.Color.Black;
            this.txtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtName.BorderColorHover = System.Drawing.Color.Black;
            this.txtName.BorderColorIdle = System.Drawing.Color.Black;
            this.txtName.BorderRadius = 10;
            this.txtName.BorderThickness = 1;
            this.txtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtName.DefaultText = "";
            this.txtName.FillColor = System.Drawing.Color.White;
            this.txtName.ForeColor = System.Drawing.Color.Black;
            this.txtName.HideSelection = true;
            this.txtName.IconLeft = null;
            this.txtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.IconPadding = 10;
            this.txtName.IconRight = null;
            this.txtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.Lines = new string[0];
            this.txtName.Location = new System.Drawing.Point(100, 50);
            this.txtName.MaxLength = 32767;
            this.txtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtName.Modified = false;
            this.txtName.Multiline = false;
            this.txtName.Name = "txtName";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Black;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Black;
            stateProperties3.FillColor = System.Drawing.Color.White;
            stateProperties3.ForeColor = System.Drawing.Color.Black;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Black;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnIdleState = stateProperties4;
            this.txtName.Padding = new System.Windows.Forms.Padding(3);
            this.txtName.PasswordChar = '\0';
            this.txtName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtName.PlaceholderText = "";
            this.txtName.ReadOnly = false;
            this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtName.SelectedText = "";
            this.txtName.SelectionLength = 0;
            this.txtName.SelectionStart = 0;
            this.txtName.ShortcutsEnabled = true;
            this.txtName.Size = new System.Drawing.Size(325, 50);
            this.txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtName.TabIndex = 0;
            this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtName.TextMarginBottom = 0;
            this.txtName.TextMarginLeft = 3;
            this.txtName.TextMarginTop = 9;
            this.txtName.TextPlaceholder = "";
            this.txtName.UseSystemPasswordChar = false;
            this.txtName.WordWrap = true;
            // 
            // elipseAccount
            // 
            this.elipseAccount.ElipseRadius = 5;
            this.elipseAccount.TargetControl = this;
            // 
            // txtSalary
            // 
            this.txtSalary.AcceptsReturn = false;
            this.txtSalary.AcceptsTab = false;
            this.txtSalary.AnimationSpeed = 200;
            this.txtSalary.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSalary.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSalary.BackColor = System.Drawing.Color.Transparent;
            this.txtSalary.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSalary.BackgroundImage")));
            this.txtSalary.BorderColorActive = System.Drawing.Color.Black;
            this.txtSalary.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSalary.BorderColorHover = System.Drawing.Color.Black;
            this.txtSalary.BorderColorIdle = System.Drawing.Color.Black;
            this.txtSalary.BorderRadius = 10;
            this.txtSalary.BorderThickness = 1;
            this.txtSalary.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSalary.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalary.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSalary.DefaultText = "";
            this.txtSalary.FillColor = System.Drawing.Color.White;
            this.txtSalary.ForeColor = System.Drawing.Color.Black;
            this.txtSalary.HideSelection = true;
            this.txtSalary.IconLeft = null;
            this.txtSalary.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalary.IconPadding = 10;
            this.txtSalary.IconRight = null;
            this.txtSalary.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalary.Lines = new string[0];
            this.txtSalary.Location = new System.Drawing.Point(550, 650);
            this.txtSalary.MaxLength = 32767;
            this.txtSalary.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSalary.Modified = false;
            this.txtSalary.Multiline = false;
            this.txtSalary.Name = "txtSalary";
            stateProperties33.BorderColor = System.Drawing.Color.Black;
            stateProperties33.FillColor = System.Drawing.Color.White;
            stateProperties33.ForeColor = System.Drawing.Color.Black;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalary.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSalary.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.Black;
            stateProperties35.FillColor = System.Drawing.Color.White;
            stateProperties35.ForeColor = System.Drawing.Color.Black;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalary.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Black;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Black;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalary.OnIdleState = stateProperties36;
            this.txtSalary.Padding = new System.Windows.Forms.Padding(3);
            this.txtSalary.PasswordChar = '\0';
            this.txtSalary.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSalary.PlaceholderText = "";
            this.txtSalary.ReadOnly = false;
            this.txtSalary.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSalary.SelectedText = "";
            this.txtSalary.SelectionLength = 0;
            this.txtSalary.SelectionStart = 0;
            this.txtSalary.ShortcutsEnabled = true;
            this.txtSalary.Size = new System.Drawing.Size(325, 50);
            this.txtSalary.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSalary.TabIndex = 1;
            this.txtSalary.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSalary.TextMarginBottom = 0;
            this.txtSalary.TextMarginLeft = 3;
            this.txtSalary.TextMarginTop = 9;
            this.txtSalary.TextPlaceholder = "";
            this.txtSalary.UseSystemPasswordChar = false;
            this.txtSalary.WordWrap = true;
            // 
            // txtExperience
            // 
            this.txtExperience.AcceptsReturn = false;
            this.txtExperience.AcceptsTab = false;
            this.txtExperience.AnimationSpeed = 200;
            this.txtExperience.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtExperience.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtExperience.BackColor = System.Drawing.Color.Transparent;
            this.txtExperience.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtExperience.BackgroundImage")));
            this.txtExperience.BorderColorActive = System.Drawing.Color.Black;
            this.txtExperience.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtExperience.BorderColorHover = System.Drawing.Color.Black;
            this.txtExperience.BorderColorIdle = System.Drawing.Color.Black;
            this.txtExperience.BorderRadius = 10;
            this.txtExperience.BorderThickness = 1;
            this.txtExperience.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtExperience.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExperience.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtExperience.DefaultText = "";
            this.txtExperience.FillColor = System.Drawing.Color.White;
            this.txtExperience.ForeColor = System.Drawing.Color.Black;
            this.txtExperience.HideSelection = true;
            this.txtExperience.IconLeft = null;
            this.txtExperience.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExperience.IconPadding = 10;
            this.txtExperience.IconRight = null;
            this.txtExperience.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExperience.Lines = new string[0];
            this.txtExperience.Location = new System.Drawing.Point(550, 550);
            this.txtExperience.MaxLength = 32767;
            this.txtExperience.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtExperience.Modified = false;
            this.txtExperience.Multiline = false;
            this.txtExperience.Name = "txtExperience";
            stateProperties29.BorderColor = System.Drawing.Color.Black;
            stateProperties29.FillColor = System.Drawing.Color.White;
            stateProperties29.ForeColor = System.Drawing.Color.Black;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExperience.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtExperience.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Black;
            stateProperties31.FillColor = System.Drawing.Color.White;
            stateProperties31.ForeColor = System.Drawing.Color.Black;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExperience.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Black;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Black;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExperience.OnIdleState = stateProperties32;
            this.txtExperience.Padding = new System.Windows.Forms.Padding(3);
            this.txtExperience.PasswordChar = '\0';
            this.txtExperience.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtExperience.PlaceholderText = "";
            this.txtExperience.ReadOnly = false;
            this.txtExperience.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtExperience.SelectedText = "";
            this.txtExperience.SelectionLength = 0;
            this.txtExperience.SelectionStart = 0;
            this.txtExperience.ShortcutsEnabled = true;
            this.txtExperience.Size = new System.Drawing.Size(325, 50);
            this.txtExperience.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtExperience.TabIndex = 2;
            this.txtExperience.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtExperience.TextMarginBottom = 0;
            this.txtExperience.TextMarginLeft = 3;
            this.txtExperience.TextMarginTop = 9;
            this.txtExperience.TextPlaceholder = "";
            this.txtExperience.UseSystemPasswordChar = false;
            this.txtExperience.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.Black;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.Black;
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Black;
            this.txtEmail.BorderRadius = 10;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.ForeColor = System.Drawing.Color.Black;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(100, 650);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties25.BorderColor = System.Drawing.Color.Black;
            stateProperties25.FillColor = System.Drawing.Color.White;
            stateProperties25.ForeColor = System.Drawing.Color.Black;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Black;
            stateProperties27.FillColor = System.Drawing.Color.White;
            stateProperties27.ForeColor = System.Drawing.Color.Black;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Black;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties28;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(325, 50);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 3;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 9;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.AnimationSpeed = 200;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.Black;
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.Black;
            this.txtPhone.BorderColorIdle = System.Drawing.Color.Black;
            this.txtPhone.BorderRadius = 10;
            this.txtPhone.BorderThickness = 1;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.White;
            this.txtPhone.ForeColor = System.Drawing.Color.Black;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = null;
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            this.txtPhone.Location = new System.Drawing.Point(100, 550);
            this.txtPhone.MaxLength = 32767;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties21.BorderColor = System.Drawing.Color.Black;
            stateProperties21.FillColor = System.Drawing.Color.White;
            stateProperties21.ForeColor = System.Drawing.Color.Black;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Black;
            stateProperties23.FillColor = System.Drawing.Color.White;
            stateProperties23.ForeColor = System.Drawing.Color.Black;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Black;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties24;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhone.PlaceholderText = "";
            this.txtPhone.ReadOnly = false;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(325, 50);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhone.TabIndex = 4;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 3;
            this.txtPhone.TextMarginTop = 9;
            this.txtPhone.TextPlaceholder = "";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            // 
            // txtAddress
            // 
            this.txtAddress.AcceptsReturn = false;
            this.txtAddress.AcceptsTab = false;
            this.txtAddress.AnimationSpeed = 200;
            this.txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddress.BackColor = System.Drawing.Color.Transparent;
            this.txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddress.BackgroundImage")));
            this.txtAddress.BorderColorActive = System.Drawing.Color.Black;
            this.txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddress.BorderColorHover = System.Drawing.Color.Black;
            this.txtAddress.BorderColorIdle = System.Drawing.Color.Black;
            this.txtAddress.BorderRadius = 10;
            this.txtAddress.BorderThickness = 1;
            this.txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAddress.DefaultText = "";
            this.txtAddress.FillColor = System.Drawing.Color.White;
            this.txtAddress.ForeColor = System.Drawing.Color.Black;
            this.txtAddress.HideSelection = true;
            this.txtAddress.IconLeft = null;
            this.txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.IconPadding = 10;
            this.txtAddress.IconRight = null;
            this.txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.Lines = new string[0];
            this.txtAddress.Location = new System.Drawing.Point(100, 450);
            this.txtAddress.MaxLength = 32767;
            this.txtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAddress.Modified = false;
            this.txtAddress.Multiline = false;
            this.txtAddress.Name = "txtAddress";
            stateProperties17.BorderColor = System.Drawing.Color.Black;
            stateProperties17.FillColor = System.Drawing.Color.White;
            stateProperties17.ForeColor = System.Drawing.Color.Black;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddress.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Black;
            stateProperties19.FillColor = System.Drawing.Color.White;
            stateProperties19.ForeColor = System.Drawing.Color.Black;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Black;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnIdleState = stateProperties20;
            this.txtAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtAddress.PasswordChar = '\0';
            this.txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.PlaceholderText = "";
            this.txtAddress.ReadOnly = false;
            this.txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddress.SelectedText = "";
            this.txtAddress.SelectionLength = 0;
            this.txtAddress.SelectionStart = 0;
            this.txtAddress.ShortcutsEnabled = true;
            this.txtAddress.Size = new System.Drawing.Size(325, 50);
            this.txtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddress.TabIndex = 5;
            this.txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddress.TextMarginBottom = 0;
            this.txtAddress.TextMarginLeft = 3;
            this.txtAddress.TextMarginTop = 9;
            this.txtAddress.TextPlaceholder = "";
            this.txtAddress.UseSystemPasswordChar = false;
            this.txtAddress.WordWrap = true;
            // 
            // txtCMND
            // 
            this.txtCMND.AcceptsReturn = false;
            this.txtCMND.AcceptsTab = false;
            this.txtCMND.AnimationSpeed = 200;
            this.txtCMND.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCMND.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCMND.BackColor = System.Drawing.Color.Transparent;
            this.txtCMND.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCMND.BackgroundImage")));
            this.txtCMND.BorderColorActive = System.Drawing.Color.Black;
            this.txtCMND.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCMND.BorderColorHover = System.Drawing.Color.Black;
            this.txtCMND.BorderColorIdle = System.Drawing.Color.Black;
            this.txtCMND.BorderRadius = 10;
            this.txtCMND.BorderThickness = 1;
            this.txtCMND.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCMND.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCMND.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCMND.DefaultText = "";
            this.txtCMND.FillColor = System.Drawing.Color.White;
            this.txtCMND.ForeColor = System.Drawing.Color.Black;
            this.txtCMND.HideSelection = true;
            this.txtCMND.IconLeft = null;
            this.txtCMND.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCMND.IconPadding = 10;
            this.txtCMND.IconRight = null;
            this.txtCMND.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCMND.Lines = new string[0];
            this.txtCMND.Location = new System.Drawing.Point(100, 350);
            this.txtCMND.MaxLength = 32767;
            this.txtCMND.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCMND.Modified = false;
            this.txtCMND.Multiline = false;
            this.txtCMND.Name = "txtCMND";
            stateProperties13.BorderColor = System.Drawing.Color.Black;
            stateProperties13.FillColor = System.Drawing.Color.White;
            stateProperties13.ForeColor = System.Drawing.Color.Black;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCMND.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCMND.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Black;
            stateProperties15.FillColor = System.Drawing.Color.White;
            stateProperties15.ForeColor = System.Drawing.Color.Black;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCMND.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCMND.OnIdleState = stateProperties16;
            this.txtCMND.Padding = new System.Windows.Forms.Padding(3);
            this.txtCMND.PasswordChar = '\0';
            this.txtCMND.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCMND.PlaceholderText = "";
            this.txtCMND.ReadOnly = false;
            this.txtCMND.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCMND.SelectedText = "";
            this.txtCMND.SelectionLength = 0;
            this.txtCMND.SelectionStart = 0;
            this.txtCMND.ShortcutsEnabled = true;
            this.txtCMND.Size = new System.Drawing.Size(325, 50);
            this.txtCMND.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCMND.TabIndex = 6;
            this.txtCMND.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCMND.TextMarginBottom = 0;
            this.txtCMND.TextMarginLeft = 3;
            this.txtCMND.TextMarginTop = 9;
            this.txtCMND.TextPlaceholder = "";
            this.txtCMND.UseSystemPasswordChar = false;
            this.txtCMND.WordWrap = true;
            // 
            // txtGender
            // 
            this.txtGender.AcceptsReturn = false;
            this.txtGender.AcceptsTab = false;
            this.txtGender.AnimationSpeed = 200;
            this.txtGender.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGender.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGender.BackColor = System.Drawing.Color.Transparent;
            this.txtGender.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGender.BackgroundImage")));
            this.txtGender.BorderColorActive = System.Drawing.Color.Black;
            this.txtGender.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtGender.BorderColorHover = System.Drawing.Color.Black;
            this.txtGender.BorderColorIdle = System.Drawing.Color.Black;
            this.txtGender.BorderRadius = 10;
            this.txtGender.BorderThickness = 1;
            this.txtGender.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGender.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGender.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtGender.DefaultText = "";
            this.txtGender.FillColor = System.Drawing.Color.White;
            this.txtGender.ForeColor = System.Drawing.Color.Black;
            this.txtGender.HideSelection = true;
            this.txtGender.IconLeft = null;
            this.txtGender.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGender.IconPadding = 10;
            this.txtGender.IconRight = null;
            this.txtGender.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGender.Lines = new string[0];
            this.txtGender.Location = new System.Drawing.Point(100, 150);
            this.txtGender.MaxLength = 32767;
            this.txtGender.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGender.Modified = false;
            this.txtGender.Multiline = false;
            this.txtGender.Name = "txtGender";
            stateProperties9.BorderColor = System.Drawing.Color.Black;
            stateProperties9.FillColor = System.Drawing.Color.White;
            stateProperties9.ForeColor = System.Drawing.Color.Black;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGender.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGender.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Black;
            stateProperties11.FillColor = System.Drawing.Color.White;
            stateProperties11.ForeColor = System.Drawing.Color.Black;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGender.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Black;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGender.OnIdleState = stateProperties12;
            this.txtGender.Padding = new System.Windows.Forms.Padding(3);
            this.txtGender.PasswordChar = '\0';
            this.txtGender.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGender.PlaceholderText = "";
            this.txtGender.ReadOnly = false;
            this.txtGender.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGender.SelectedText = "";
            this.txtGender.SelectionLength = 0;
            this.txtGender.SelectionStart = 0;
            this.txtGender.ShortcutsEnabled = true;
            this.txtGender.Size = new System.Drawing.Size(325, 50);
            this.txtGender.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGender.TabIndex = 7;
            this.txtGender.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGender.TextMarginBottom = 0;
            this.txtGender.TextMarginLeft = 3;
            this.txtGender.TextMarginTop = 9;
            this.txtGender.TextPlaceholder = "";
            this.txtGender.UseSystemPasswordChar = false;
            this.txtGender.WordWrap = true;
            // 
            // dtpBirthdate
            // 
            this.dtpBirthdate.BackColor = System.Drawing.Color.Transparent;
            this.dtpBirthdate.BorderRadius = 1;
            this.dtpBirthdate.Color = System.Drawing.Color.Transparent;
            this.dtpBirthdate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtpBirthdate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtpBirthdate.DisabledColor = System.Drawing.Color.Gray;
            this.dtpBirthdate.DisplayWeekNumbers = false;
            this.dtpBirthdate.DPHeight = 0;
            this.dtpBirthdate.FillDatePicker = false;
            this.dtpBirthdate.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpBirthdate.ForeColor = System.Drawing.Color.Black;
            this.dtpBirthdate.Icon = ((System.Drawing.Image)(resources.GetObject("dtpBirthdate.Icon")));
            this.dtpBirthdate.IconColor = System.Drawing.Color.Navy;
            this.dtpBirthdate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtpBirthdate.LeftTextMargin = 0;
            this.dtpBirthdate.Location = new System.Drawing.Point(105, 264);
            this.dtpBirthdate.MinimumSize = new System.Drawing.Size(0, 32);
            this.dtpBirthdate.Name = "dtpBirthdate";
            this.dtpBirthdate.Size = new System.Drawing.Size(300, 34);
            this.dtpBirthdate.TabIndex = 8;
            this.dtpBirthdate.Value = new System.DateTime(2024, 3, 18, 19, 52, 0, 0);
            // 
            // pnBirthdate
            // 
            this.pnBirthdate.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnBirthdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnBirthdate.BackgroundImage")));
            this.pnBirthdate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnBirthdate.BorderColor = System.Drawing.Color.Black;
            this.pnBirthdate.BorderRadius = 10;
            this.pnBirthdate.BorderThickness = 1;
            this.pnBirthdate.Location = new System.Drawing.Point(100, 250);
            this.pnBirthdate.Name = "pnBirthdate";
            this.pnBirthdate.ShowBorders = true;
            this.pnBirthdate.Size = new System.Drawing.Size(325, 50);
            this.pnBirthdate.TabIndex = 9;
            // 
            // lblGender
            // 
            this.lblGender.AllowParentOverrides = false;
            this.lblGender.AutoEllipsis = false;
            this.lblGender.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblGender.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblGender.ForeColor = System.Drawing.Color.Black;
            this.lblGender.Location = new System.Drawing.Point(115, 135);
            this.lblGender.Name = "lblGender";
            this.lblGender.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblGender.Size = new System.Drawing.Size(76, 25);
            this.lblGender.TabIndex = 10;
            this.lblGender.Text = "Gender";
            this.lblGender.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblGender.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblName
            // 
            this.lblName.AllowParentOverrides = false;
            this.lblName.AutoEllipsis = false;
            this.lblName.CursorType = null;
            this.lblName.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblName.ForeColor = System.Drawing.Color.Black;
            this.lblName.Location = new System.Drawing.Point(115, 35);
            this.lblName.Name = "lblName";
            this.lblName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblName.Size = new System.Drawing.Size(59, 25);
            this.lblName.TabIndex = 11;
            this.lblName.Text = "Name";
            this.lblName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblBirthdate
            // 
            this.lblBirthdate.AllowParentOverrides = false;
            this.lblBirthdate.AutoEllipsis = false;
            this.lblBirthdate.CursorType = null;
            this.lblBirthdate.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblBirthdate.ForeColor = System.Drawing.Color.Black;
            this.lblBirthdate.Location = new System.Drawing.Point(115, 235);
            this.lblBirthdate.Name = "lblBirthdate";
            this.lblBirthdate.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblBirthdate.Size = new System.Drawing.Size(96, 25);
            this.lblBirthdate.TabIndex = 12;
            this.lblBirthdate.Text = "Birthdate";
            this.lblBirthdate.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblBirthdate.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblCMND
            // 
            this.lblCMND.AllowParentOverrides = false;
            this.lblCMND.AutoEllipsis = false;
            this.lblCMND.CursorType = null;
            this.lblCMND.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblCMND.ForeColor = System.Drawing.Color.Black;
            this.lblCMND.Location = new System.Drawing.Point(115, 335);
            this.lblCMND.Name = "lblCMND";
            this.lblCMND.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblCMND.Size = new System.Drawing.Size(74, 25);
            this.lblCMND.TabIndex = 13;
            this.lblCMND.Text = "CMND";
            this.lblCMND.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblCMND.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblAddress
            // 
            this.lblAddress.AllowParentOverrides = false;
            this.lblAddress.AutoEllipsis = false;
            this.lblAddress.CursorType = null;
            this.lblAddress.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblAddress.ForeColor = System.Drawing.Color.Black;
            this.lblAddress.Location = new System.Drawing.Point(115, 435);
            this.lblAddress.Name = "lblAddress";
            this.lblAddress.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblAddress.Size = new System.Drawing.Size(81, 25);
            this.lblAddress.TabIndex = 14;
            this.lblAddress.Text = "Address";
            this.lblAddress.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblAddress.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblPhone
            // 
            this.lblPhone.AllowParentOverrides = false;
            this.lblPhone.AutoEllipsis = false;
            this.lblPhone.CursorType = null;
            this.lblPhone.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblPhone.ForeColor = System.Drawing.Color.Black;
            this.lblPhone.Location = new System.Drawing.Point(115, 535);
            this.lblPhone.Name = "lblPhone";
            this.lblPhone.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPhone.Size = new System.Drawing.Size(149, 25);
            this.lblPhone.TabIndex = 15;
            this.lblPhone.Text = "Phone number";
            this.lblPhone.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPhone.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblEmail
            // 
            this.lblEmail.AllowParentOverrides = false;
            this.lblEmail.AutoEllipsis = false;
            this.lblEmail.CursorType = null;
            this.lblEmail.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblEmail.ForeColor = System.Drawing.Color.Black;
            this.lblEmail.Location = new System.Drawing.Point(115, 635);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblEmail.Size = new System.Drawing.Size(56, 25);
            this.lblEmail.TabIndex = 16;
            this.lblEmail.Text = "Email";
            this.lblEmail.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblEmail.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblExperience
            // 
            this.lblExperience.AllowParentOverrides = false;
            this.lblExperience.AutoEllipsis = false;
            this.lblExperience.CursorType = null;
            this.lblExperience.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblExperience.ForeColor = System.Drawing.Color.Black;
            this.lblExperience.Location = new System.Drawing.Point(565, 535);
            this.lblExperience.Name = "lblExperience";
            this.lblExperience.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblExperience.Size = new System.Drawing.Size(186, 25);
            this.lblExperience.TabIndex = 17;
            this.lblExperience.Text = "Experience (years)";
            this.lblExperience.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblExperience.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblSalary
            // 
            this.lblSalary.AllowParentOverrides = false;
            this.lblSalary.AutoEllipsis = false;
            this.lblSalary.CursorType = null;
            this.lblSalary.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblSalary.ForeColor = System.Drawing.Color.Black;
            this.lblSalary.Location = new System.Drawing.Point(565, 635);
            this.lblSalary.Name = "lblSalary";
            this.lblSalary.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblSalary.Size = new System.Drawing.Size(158, 25);
            this.lblSalary.TabIndex = 18;
            this.lblSalary.Text = "Expected salary";
            this.lblSalary.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblSalary.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // drdCertificate
            // 
            this.drdCertificate.BackColor = System.Drawing.Color.Transparent;
            this.drdCertificate.BackgroundColor = System.Drawing.Color.White;
            this.drdCertificate.BorderColor = System.Drawing.Color.Transparent;
            this.drdCertificate.BorderRadius = 1;
            this.drdCertificate.Color = System.Drawing.Color.Transparent;
            this.drdCertificate.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.drdCertificate.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drdCertificate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drdCertificate.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drdCertificate.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.drdCertificate.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.drdCertificate.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.drdCertificate.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.drdCertificate.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.drdCertificate.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drdCertificate.FillDropDown = true;
            this.drdCertificate.FillIndicator = false;
            this.drdCertificate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.drdCertificate.Font = new System.Drawing.Font("Times New Roman", 13.8F);
            this.drdCertificate.ForeColor = System.Drawing.Color.Black;
            this.drdCertificate.FormattingEnabled = true;
            this.drdCertificate.Icon = null;
            this.drdCertificate.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drdCertificate.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.drdCertificate.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drdCertificate.ItemBackColor = System.Drawing.Color.White;
            this.drdCertificate.ItemBorderColor = System.Drawing.Color.White;
            this.drdCertificate.ItemForeColor = System.Drawing.Color.Black;
            this.drdCertificate.ItemHeight = 26;
            this.drdCertificate.ItemHighLightColor = System.Drawing.Color.White;
            this.drdCertificate.ItemHighLightForeColor = System.Drawing.Color.Black;
            this.drdCertificate.ItemTopMargin = 3;
            this.drdCertificate.Location = new System.Drawing.Point(2, 15);
            this.drdCertificate.Name = "drdCertificate";
            this.drdCertificate.Size = new System.Drawing.Size(319, 32);
            this.drdCertificate.TabIndex = 19;
            this.drdCertificate.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drdCertificate.TextLeftMargin = 5;
            // 
            // drdOccupation
            // 
            this.drdOccupation.BackColor = System.Drawing.Color.Transparent;
            this.drdOccupation.BackgroundColor = System.Drawing.Color.White;
            this.drdOccupation.BorderColor = System.Drawing.Color.Transparent;
            this.drdOccupation.BorderRadius = 1;
            this.drdOccupation.Color = System.Drawing.Color.Transparent;
            this.drdOccupation.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.drdOccupation.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drdOccupation.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drdOccupation.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drdOccupation.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.drdOccupation.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.drdOccupation.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.drdOccupation.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.drdOccupation.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.drdOccupation.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drdOccupation.FillDropDown = true;
            this.drdOccupation.FillIndicator = false;
            this.drdOccupation.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.drdOccupation.Font = new System.Drawing.Font("Times New Roman", 13.8F);
            this.drdOccupation.ForeColor = System.Drawing.Color.Black;
            this.drdOccupation.FormattingEnabled = true;
            this.drdOccupation.Icon = null;
            this.drdOccupation.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drdOccupation.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.drdOccupation.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drdOccupation.ItemBackColor = System.Drawing.Color.White;
            this.drdOccupation.ItemBorderColor = System.Drawing.Color.White;
            this.drdOccupation.ItemForeColor = System.Drawing.Color.Black;
            this.drdOccupation.ItemHeight = 26;
            this.drdOccupation.ItemHighLightColor = System.Drawing.Color.White;
            this.drdOccupation.ItemHighLightForeColor = System.Drawing.Color.Black;
            this.drdOccupation.ItemTopMargin = 3;
            this.drdOccupation.Location = new System.Drawing.Point(2, 15);
            this.drdOccupation.Name = "drdOccupation";
            this.drdOccupation.Size = new System.Drawing.Size(319, 32);
            this.drdOccupation.TabIndex = 20;
            this.drdOccupation.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drdOccupation.TextLeftMargin = 0;
            // 
            // pnCertificate
            // 
            this.pnCertificate.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnCertificate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnCertificate.BackgroundImage")));
            this.pnCertificate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnCertificate.BorderColor = System.Drawing.Color.Black;
            this.pnCertificate.BorderRadius = 10;
            this.pnCertificate.BorderThickness = 1;
            this.pnCertificate.Controls.Add(this.drdCertificate);
            this.pnCertificate.Location = new System.Drawing.Point(550, 450);
            this.pnCertificate.Name = "pnCertificate";
            this.pnCertificate.ShowBorders = true;
            this.pnCertificate.Size = new System.Drawing.Size(325, 50);
            this.pnCertificate.TabIndex = 21;
            // 
            // pnOccupation
            // 
            this.pnOccupation.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnOccupation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnOccupation.BackgroundImage")));
            this.pnOccupation.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnOccupation.BorderColor = System.Drawing.Color.Black;
            this.pnOccupation.BorderRadius = 10;
            this.pnOccupation.BorderThickness = 1;
            this.pnOccupation.Controls.Add(this.drdOccupation);
            this.pnOccupation.Location = new System.Drawing.Point(550, 350);
            this.pnOccupation.Name = "pnOccupation";
            this.pnOccupation.ShowBorders = true;
            this.pnOccupation.Size = new System.Drawing.Size(325, 50);
            this.pnOccupation.TabIndex = 22;
            // 
            // lblOccupation
            // 
            this.lblOccupation.AllowParentOverrides = false;
            this.lblOccupation.AutoEllipsis = false;
            this.lblOccupation.CursorType = null;
            this.lblOccupation.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblOccupation.ForeColor = System.Drawing.Color.Black;
            this.lblOccupation.Location = new System.Drawing.Point(565, 335);
            this.lblOccupation.Name = "lblOccupation";
            this.lblOccupation.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblOccupation.Size = new System.Drawing.Size(116, 25);
            this.lblOccupation.TabIndex = 23;
            this.lblOccupation.Text = "Occupation";
            this.lblOccupation.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblOccupation.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblCertificate
            // 
            this.lblCertificate.AllowParentOverrides = false;
            this.lblCertificate.AutoEllipsis = false;
            this.lblCertificate.CursorType = null;
            this.lblCertificate.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblCertificate.ForeColor = System.Drawing.Color.Black;
            this.lblCertificate.Location = new System.Drawing.Point(565, 435);
            this.lblCertificate.Name = "lblCertificate";
            this.lblCertificate.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblCertificate.Size = new System.Drawing.Size(106, 25);
            this.lblCertificate.TabIndex = 24;
            this.lblCertificate.Text = "Certificate";
            this.lblCertificate.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblCertificate.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblBio
            // 
            this.lblBio.AllowParentOverrides = false;
            this.lblBio.AutoEllipsis = false;
            this.lblBio.CursorType = null;
            this.lblBio.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold);
            this.lblBio.ForeColor = System.Drawing.Color.Black;
            this.lblBio.Location = new System.Drawing.Point(565, 38);
            this.lblBio.Name = "lblBio";
            this.lblBio.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblBio.Size = new System.Drawing.Size(33, 25);
            this.lblBio.TabIndex = 26;
            this.lblBio.Text = "Bio";
            this.lblBio.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblBio.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtBio
            // 
            this.txtBio.AcceptsReturn = false;
            this.txtBio.AcceptsTab = false;
            this.txtBio.AnimationSpeed = 200;
            this.txtBio.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBio.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBio.BackColor = System.Drawing.Color.Transparent;
            this.txtBio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBio.BackgroundImage")));
            this.txtBio.BorderColorActive = System.Drawing.Color.Black;
            this.txtBio.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBio.BorderColorHover = System.Drawing.Color.Black;
            this.txtBio.BorderColorIdle = System.Drawing.Color.Navy;
            this.txtBio.BorderRadius = 45;
            this.txtBio.BorderThickness = 3;
            this.txtBio.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBio.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBio.DefaultFont = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBio.DefaultText = "";
            this.txtBio.FillColor = System.Drawing.Color.White;
            this.txtBio.ForeColor = System.Drawing.Color.Black;
            this.txtBio.HideSelection = true;
            this.txtBio.IconLeft = null;
            this.txtBio.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBio.IconPadding = 10;
            this.txtBio.IconRight = null;
            this.txtBio.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBio.Lines = new string[0];
            this.txtBio.Location = new System.Drawing.Point(483, 50);
            this.txtBio.MaxLength = 32767;
            this.txtBio.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBio.Modified = false;
            this.txtBio.Multiline = true;
            this.txtBio.Name = "txtBio";
            stateProperties5.BorderColor = System.Drawing.Color.Black;
            stateProperties5.FillColor = System.Drawing.Color.White;
            stateProperties5.ForeColor = System.Drawing.Color.Black;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBio.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBio.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Black;
            stateProperties7.FillColor = System.Drawing.Color.White;
            stateProperties7.ForeColor = System.Drawing.Color.Black;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBio.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Navy;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBio.OnIdleState = stateProperties8;
            this.txtBio.Padding = new System.Windows.Forms.Padding(3);
            this.txtBio.PasswordChar = '\0';
            this.txtBio.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBio.PlaceholderText = "";
            this.txtBio.ReadOnly = false;
            this.txtBio.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBio.SelectedText = "";
            this.txtBio.SelectionLength = 0;
            this.txtBio.SelectionStart = 0;
            this.txtBio.ShortcutsEnabled = true;
            this.txtBio.Size = new System.Drawing.Size(450, 248);
            this.txtBio.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBio.TabIndex = 27;
            this.txtBio.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBio.TextMarginBottom = 0;
            this.txtBio.TextMarginLeft = 3;
            this.txtBio.TextMarginTop = 0;
            this.txtBio.TextPlaceholder = "";
            this.txtBio.UseSystemPasswordChar = false;
            this.txtBio.WordWrap = true;
            // 
            // pnRegister
            // 
            this.pnRegister.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnRegister.BackgroundImage")));
            this.pnRegister.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnRegister.BorderColor = System.Drawing.Color.Blue;
            this.pnRegister.BorderRadius = 30;
            this.pnRegister.BorderThickness = 10;
            this.pnRegister.Controls.Add(this.btnRegister);
            this.pnRegister.Location = new System.Drawing.Point(483, 310);
            this.pnRegister.Name = "pnRegister";
            this.pnRegister.ShowBorders = true;
            this.pnRegister.Size = new System.Drawing.Size(450, 561);
            this.pnRegister.TabIndex = 28;
            // 
            // btnChangeInfo
            // 
            this.btnChangeInfo.AllowAnimations = true;
            this.btnChangeInfo.AllowMouseEffects = true;
            this.btnChangeInfo.AllowToggling = false;
            this.btnChangeInfo.AnimationSpeed = 200;
            this.btnChangeInfo.AutoGenerateColors = false;
            this.btnChangeInfo.AutoRoundBorders = false;
            this.btnChangeInfo.AutoSizeLeftIcon = true;
            this.btnChangeInfo.AutoSizeRightIcon = true;
            this.btnChangeInfo.BackColor = System.Drawing.Color.Transparent;
            this.btnChangeInfo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnChangeInfo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangeInfo.BackgroundImage")));
            this.btnChangeInfo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeInfo.ButtonText = "Change you information";
            this.btnChangeInfo.ButtonTextMarginLeft = 0;
            this.btnChangeInfo.ColorContrastOnClick = 45;
            this.btnChangeInfo.ColorContrastOnHover = 45;
            this.btnChangeInfo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnChangeInfo.CustomizableEdges = borderEdges1;
            this.btnChangeInfo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangeInfo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnChangeInfo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnChangeInfo.DisabledForecolor = System.Drawing.Color.White;
            this.btnChangeInfo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangeInfo.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChangeInfo.ForeColor = System.Drawing.Color.White;
            this.btnChangeInfo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangeInfo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeInfo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChangeInfo.IconMarginLeft = 11;
            this.btnChangeInfo.IconPadding = 10;
            this.btnChangeInfo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangeInfo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeInfo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChangeInfo.IconSize = 25;
            this.btnChangeInfo.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnChangeInfo.IdleBorderRadius = 30;
            this.btnChangeInfo.IdleBorderThickness = 1;
            this.btnChangeInfo.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnChangeInfo.IdleIconLeftImage = null;
            this.btnChangeInfo.IdleIconRightImage = null;
            this.btnChangeInfo.IndicateFocus = false;
            this.btnChangeInfo.Location = new System.Drawing.Point(100, 725);
            this.btnChangeInfo.Name = "btnChangeInfo";
            this.btnChangeInfo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnChangeInfo.OnDisabledState.BorderRadius = 30;
            this.btnChangeInfo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeInfo.OnDisabledState.BorderThickness = 1;
            this.btnChangeInfo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnChangeInfo.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnChangeInfo.OnDisabledState.IconLeftImage = null;
            this.btnChangeInfo.OnDisabledState.IconRightImage = null;
            this.btnChangeInfo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnChangeInfo.onHoverState.BorderRadius = 30;
            this.btnChangeInfo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeInfo.onHoverState.BorderThickness = 1;
            this.btnChangeInfo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnChangeInfo.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnChangeInfo.onHoverState.IconLeftImage = null;
            this.btnChangeInfo.onHoverState.IconRightImage = null;
            this.btnChangeInfo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnChangeInfo.OnIdleState.BorderRadius = 30;
            this.btnChangeInfo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeInfo.OnIdleState.BorderThickness = 1;
            this.btnChangeInfo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnChangeInfo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChangeInfo.OnIdleState.IconLeftImage = null;
            this.btnChangeInfo.OnIdleState.IconRightImage = null;
            this.btnChangeInfo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnChangeInfo.OnPressedState.BorderRadius = 30;
            this.btnChangeInfo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeInfo.OnPressedState.BorderThickness = 1;
            this.btnChangeInfo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnChangeInfo.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnChangeInfo.OnPressedState.IconLeftImage = null;
            this.btnChangeInfo.OnPressedState.IconRightImage = null;
            this.btnChangeInfo.Size = new System.Drawing.Size(320, 50);
            this.btnChangeInfo.TabIndex = 29;
            this.btnChangeInfo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangeInfo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangeInfo.TextMarginLeft = 0;
            this.btnChangeInfo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangeInfo.UseDefaultRadiusAndThickness = true;
            // 
            // btnRegister
            // 
            this.btnRegister.AllowAnimations = true;
            this.btnRegister.AllowMouseEffects = true;
            this.btnRegister.AllowToggling = false;
            this.btnRegister.AnimationSpeed = 200;
            this.btnRegister.AutoGenerateColors = false;
            this.btnRegister.AutoRoundBorders = false;
            this.btnRegister.AutoSizeLeftIcon = true;
            this.btnRegister.AutoSizeRightIcon = true;
            this.btnRegister.BackColor = System.Drawing.Color.Transparent;
            this.btnRegister.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRegister.BackgroundImage")));
            this.btnRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.ButtonText = "Register as a Worker";
            this.btnRegister.ButtonTextMarginLeft = 0;
            this.btnRegister.ColorContrastOnClick = 45;
            this.btnRegister.ColorContrastOnHover = 45;
            this.btnRegister.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnRegister.CustomizableEdges = borderEdges2;
            this.btnRegister.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRegister.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnRegister.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnRegister.DisabledForecolor = System.Drawing.Color.White;
            this.btnRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRegister.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRegister.ForeColor = System.Drawing.Color.White;
            this.btnRegister.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRegister.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegister.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRegister.IconMarginLeft = 11;
            this.btnRegister.IconPadding = 10;
            this.btnRegister.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRegister.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegister.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRegister.IconSize = 25;
            this.btnRegister.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnRegister.IdleBorderRadius = 30;
            this.btnRegister.IdleBorderThickness = 1;
            this.btnRegister.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnRegister.IdleIconLeftImage = null;
            this.btnRegister.IdleIconRightImage = null;
            this.btnRegister.IndicateFocus = false;
            this.btnRegister.Location = new System.Drawing.Point(67, 415);
            this.btnRegister.Name = "btnRegister";
            this.btnRegister.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnRegister.OnDisabledState.BorderRadius = 30;
            this.btnRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.OnDisabledState.BorderThickness = 1;
            this.btnRegister.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnRegister.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnRegister.OnDisabledState.IconLeftImage = null;
            this.btnRegister.OnDisabledState.IconRightImage = null;
            this.btnRegister.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnRegister.onHoverState.BorderRadius = 30;
            this.btnRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.onHoverState.BorderThickness = 1;
            this.btnRegister.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnRegister.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnRegister.onHoverState.IconLeftImage = null;
            this.btnRegister.onHoverState.IconRightImage = null;
            this.btnRegister.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnRegister.OnIdleState.BorderRadius = 30;
            this.btnRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.OnIdleState.BorderThickness = 1;
            this.btnRegister.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnRegister.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRegister.OnIdleState.IconLeftImage = null;
            this.btnRegister.OnIdleState.IconRightImage = null;
            this.btnRegister.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnRegister.OnPressedState.BorderRadius = 30;
            this.btnRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegister.OnPressedState.BorderThickness = 1;
            this.btnRegister.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.btnRegister.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnRegister.OnPressedState.IconLeftImage = null;
            this.btnRegister.OnPressedState.IconRightImage = null;
            this.btnRegister.Size = new System.Drawing.Size(320, 50);
            this.btnRegister.TabIndex = 30;
            this.btnRegister.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRegister.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRegister.TextMarginLeft = 0;
            this.btnRegister.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRegister.UseDefaultRadiusAndThickness = true;
            // 
            // ucAccount
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.btnChangeInfo);
            this.Controls.Add(this.lblBio);
            this.Controls.Add(this.txtBio);
            this.Controls.Add(this.lblCertificate);
            this.Controls.Add(this.lblOccupation);
            this.Controls.Add(this.pnOccupation);
            this.Controls.Add(this.pnCertificate);
            this.Controls.Add(this.lblSalary);
            this.Controls.Add(this.lblExperience);
            this.Controls.Add(this.lblEmail);
            this.Controls.Add(this.lblPhone);
            this.Controls.Add(this.lblAddress);
            this.Controls.Add(this.lblCMND);
            this.Controls.Add(this.lblBirthdate);
            this.Controls.Add(this.lblName);
            this.Controls.Add(this.lblGender);
            this.Controls.Add(this.dtpBirthdate);
            this.Controls.Add(this.pnBirthdate);
            this.Controls.Add(this.txtGender);
            this.Controls.Add(this.txtCMND);
            this.Controls.Add(this.txtAddress);
            this.Controls.Add(this.txtPhone);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.txtExperience);
            this.Controls.Add(this.txtSalary);
            this.Controls.Add(this.txtName);
            this.Controls.Add(this.pnRegister);
            this.Name = "ucAccount";
            this.Size = new System.Drawing.Size(980, 800);
            this.pnCertificate.ResumeLayout(false);
            this.pnOccupation.ResumeLayout(false);
            this.pnRegister.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtName;
        private Bunifu.Framework.UI.BunifuElipse elipseAccount;
        private Bunifu.UI.WinForms.BunifuDatePicker dtpBirthdate;
        private Bunifu.UI.WinForms.BunifuTextBox txtGender;
        private Bunifu.UI.WinForms.BunifuTextBox txtCMND;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddress;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhone;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtExperience;
        private Bunifu.UI.WinForms.BunifuTextBox txtSalary;
        private Bunifu.UI.WinForms.BunifuPanel pnBirthdate;
        private Bunifu.UI.WinForms.BunifuLabel lblName;
        private Bunifu.UI.WinForms.BunifuLabel lblGender;
        private Bunifu.UI.WinForms.BunifuLabel lblSalary;
        private Bunifu.UI.WinForms.BunifuLabel lblExperience;
        private Bunifu.UI.WinForms.BunifuLabel lblEmail;
        private Bunifu.UI.WinForms.BunifuLabel lblPhone;
        private Bunifu.UI.WinForms.BunifuLabel lblAddress;
        private Bunifu.UI.WinForms.BunifuLabel lblCMND;
        private Bunifu.UI.WinForms.BunifuLabel lblBirthdate;
        private Bunifu.UI.WinForms.BunifuPanel pnOccupation;
        private Bunifu.UI.WinForms.BunifuDropdown drdOccupation;
        private Bunifu.UI.WinForms.BunifuPanel pnCertificate;
        private Bunifu.UI.WinForms.BunifuDropdown drdCertificate;
        private Bunifu.UI.WinForms.BunifuLabel lblCertificate;
        private Bunifu.UI.WinForms.BunifuLabel lblOccupation;
        private Bunifu.UI.WinForms.BunifuLabel lblBio;
        private Bunifu.UI.WinForms.BunifuTextBox txtBio;
        private Bunifu.UI.WinForms.BunifuPanel pnRegister;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangeInfo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRegister;
    }
}
