namespace WPFinalPlease
{
    partial class ucMainMenu
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucMainMenu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.btnAccountSetting = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnTurnOff = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNotification = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOngoingWork = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnWorkerList = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnJobList = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnChangeAvatar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pBoxAvatar = new System.Windows.Forms.PictureBox();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pBoxAvatar)).BeginInit();
            this.SuspendLayout();
            // 
            // btnAccountSetting
            // 
            this.btnAccountSetting.AllowAnimations = true;
            this.btnAccountSetting.AllowMouseEffects = true;
            this.btnAccountSetting.AllowToggling = false;
            this.btnAccountSetting.AnimationSpeed = 200;
            this.btnAccountSetting.AutoGenerateColors = false;
            this.btnAccountSetting.AutoRoundBorders = false;
            this.btnAccountSetting.AutoSizeLeftIcon = true;
            this.btnAccountSetting.AutoSizeRightIcon = true;
            this.btnAccountSetting.BackColor = System.Drawing.Color.Transparent;
            this.btnAccountSetting.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnAccountSetting.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAccountSetting.BackgroundImage")));
            this.btnAccountSetting.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountSetting.ButtonText = "Account Setting";
            this.btnAccountSetting.ButtonTextMarginLeft = 0;
            this.btnAccountSetting.ColorContrastOnClick = 45;
            this.btnAccountSetting.ColorContrastOnHover = 45;
            this.btnAccountSetting.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAccountSetting.CustomizableEdges = borderEdges1;
            this.btnAccountSetting.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAccountSetting.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAccountSetting.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAccountSetting.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAccountSetting.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAccountSetting.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAccountSetting.ForeColor = System.Drawing.Color.Black;
            this.btnAccountSetting.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAccountSetting.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAccountSetting.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAccountSetting.IconMarginLeft = 11;
            this.btnAccountSetting.IconPadding = 10;
            this.btnAccountSetting.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAccountSetting.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAccountSetting.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAccountSetting.IconSize = 25;
            this.btnAccountSetting.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnAccountSetting.IdleBorderRadius = 1;
            this.btnAccountSetting.IdleBorderThickness = 1;
            this.btnAccountSetting.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnAccountSetting.IdleIconLeftImage = null;
            this.btnAccountSetting.IdleIconRightImage = null;
            this.btnAccountSetting.IndicateFocus = false;
            this.btnAccountSetting.Location = new System.Drawing.Point(0, 410);
            this.btnAccountSetting.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnAccountSetting.Name = "btnAccountSetting";
            this.btnAccountSetting.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAccountSetting.OnDisabledState.BorderRadius = 1;
            this.btnAccountSetting.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountSetting.OnDisabledState.BorderThickness = 1;
            this.btnAccountSetting.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAccountSetting.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAccountSetting.OnDisabledState.IconLeftImage = null;
            this.btnAccountSetting.OnDisabledState.IconRightImage = null;
            this.btnAccountSetting.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAccountSetting.onHoverState.BorderRadius = 1;
            this.btnAccountSetting.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountSetting.onHoverState.BorderThickness = 1;
            this.btnAccountSetting.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAccountSetting.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAccountSetting.onHoverState.IconLeftImage = null;
            this.btnAccountSetting.onHoverState.IconRightImage = null;
            this.btnAccountSetting.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnAccountSetting.OnIdleState.BorderRadius = 1;
            this.btnAccountSetting.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountSetting.OnIdleState.BorderThickness = 1;
            this.btnAccountSetting.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnAccountSetting.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnAccountSetting.OnIdleState.IconLeftImage = null;
            this.btnAccountSetting.OnIdleState.IconRightImage = null;
            this.btnAccountSetting.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAccountSetting.OnPressedState.BorderRadius = 1;
            this.btnAccountSetting.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountSetting.OnPressedState.BorderThickness = 1;
            this.btnAccountSetting.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAccountSetting.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAccountSetting.OnPressedState.IconLeftImage = null;
            this.btnAccountSetting.OnPressedState.IconRightImage = null;
            this.btnAccountSetting.Size = new System.Drawing.Size(225, 41);
            this.btnAccountSetting.TabIndex = 5;
            this.btnAccountSetting.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAccountSetting.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAccountSetting.TextMarginLeft = 0;
            this.btnAccountSetting.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAccountSetting.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(153)))), ((int)(((byte)(255)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(153)))), ((int)(((byte)(255)))));
            this.bunifuPanel1.BorderRadius = 0;
            this.bunifuPanel1.BorderThickness = 0;
            this.bunifuPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel1.Controls.Add(this.btnNotification);
            this.bunifuPanel1.Controls.Add(this.btnOngoingWork);
            this.bunifuPanel1.Controls.Add(this.btnWorkerList);
            this.bunifuPanel1.Controls.Add(this.btnJobList);
            this.bunifuPanel1.Controls.Add(this.btnChangeAvatar);
            this.bunifuPanel1.Controls.Add(this.pBoxAvatar);
            this.bunifuPanel1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(225, 650);
            this.bunifuPanel1.TabIndex = 0;
            this.bunifuPanel1.Click += new System.EventHandler(this.bunifuPanel1_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(28)))), ((int)(((byte)(101)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(28)))), ((int)(((byte)(101)))));
            this.bunifuPanel2.BorderRadius = 0;
            this.bunifuPanel2.BorderThickness = 0;
            this.bunifuPanel2.Controls.Add(this.btnTurnOff);
            this.bunifuPanel2.Controls.Add(this.btnLogout);
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 488);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = false;
            this.bunifuPanel2.Size = new System.Drawing.Size(225, 162);
            this.bunifuPanel2.TabIndex = 6;
            // 
            // btnTurnOff
            // 
            this.btnTurnOff.AllowAnimations = true;
            this.btnTurnOff.AllowMouseEffects = true;
            this.btnTurnOff.AllowToggling = false;
            this.btnTurnOff.AnimationSpeed = 200;
            this.btnTurnOff.AutoGenerateColors = false;
            this.btnTurnOff.AutoRoundBorders = true;
            this.btnTurnOff.AutoSizeLeftIcon = true;
            this.btnTurnOff.AutoSizeRightIcon = true;
            this.btnTurnOff.BackColor = System.Drawing.Color.Transparent;
            this.btnTurnOff.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnTurnOff.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTurnOff.BackgroundImage")));
            this.btnTurnOff.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTurnOff.ButtonText = "Turn Off";
            this.btnTurnOff.ButtonTextMarginLeft = 0;
            this.btnTurnOff.ColorContrastOnClick = 45;
            this.btnTurnOff.ColorContrastOnHover = 45;
            this.btnTurnOff.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnTurnOff.CustomizableEdges = borderEdges2;
            this.btnTurnOff.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTurnOff.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTurnOff.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTurnOff.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTurnOff.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTurnOff.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTurnOff.ForeColor = System.Drawing.Color.White;
            this.btnTurnOff.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTurnOff.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTurnOff.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTurnOff.IconMarginLeft = 11;
            this.btnTurnOff.IconPadding = 5;
            this.btnTurnOff.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTurnOff.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTurnOff.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTurnOff.IconSize = 25;
            this.btnTurnOff.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnTurnOff.IdleBorderRadius = 30;
            this.btnTurnOff.IdleBorderThickness = 1;
            this.btnTurnOff.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnTurnOff.IdleIconLeftImage = global::WPFinalPlease.Properties.Resources.icons8_power_off_button_100;
            this.btnTurnOff.IdleIconRightImage = null;
            this.btnTurnOff.IndicateFocus = false;
            this.btnTurnOff.Location = new System.Drawing.Point(29, 93);
            this.btnTurnOff.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnTurnOff.Name = "btnTurnOff";
            this.btnTurnOff.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTurnOff.OnDisabledState.BorderRadius = 1;
            this.btnTurnOff.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTurnOff.OnDisabledState.BorderThickness = 1;
            this.btnTurnOff.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTurnOff.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTurnOff.OnDisabledState.IconLeftImage = null;
            this.btnTurnOff.OnDisabledState.IconRightImage = null;
            this.btnTurnOff.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTurnOff.onHoverState.BorderRadius = 1;
            this.btnTurnOff.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTurnOff.onHoverState.BorderThickness = 1;
            this.btnTurnOff.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTurnOff.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTurnOff.onHoverState.IconLeftImage = null;
            this.btnTurnOff.onHoverState.IconRightImage = null;
            this.btnTurnOff.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnTurnOff.OnIdleState.BorderRadius = 1;
            this.btnTurnOff.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTurnOff.OnIdleState.BorderThickness = 1;
            this.btnTurnOff.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnTurnOff.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTurnOff.OnIdleState.IconLeftImage = global::WPFinalPlease.Properties.Resources.icons8_power_off_button_100;
            this.btnTurnOff.OnIdleState.IconRightImage = null;
            this.btnTurnOff.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTurnOff.OnPressedState.BorderRadius = 1;
            this.btnTurnOff.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTurnOff.OnPressedState.BorderThickness = 1;
            this.btnTurnOff.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTurnOff.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTurnOff.OnPressedState.IconLeftImage = null;
            this.btnTurnOff.OnPressedState.IconRightImage = null;
            this.btnTurnOff.Size = new System.Drawing.Size(165, 32);
            this.btnTurnOff.TabIndex = 7;
            this.btnTurnOff.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTurnOff.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTurnOff.TextMarginLeft = 0;
            this.btnTurnOff.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTurnOff.UseDefaultRadiusAndThickness = true;
            // 
            // btnLogout
            // 
            this.btnLogout.AllowAnimations = true;
            this.btnLogout.AllowMouseEffects = true;
            this.btnLogout.AllowToggling = false;
            this.btnLogout.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnLogout.AnimationSpeed = 200;
            this.btnLogout.AutoGenerateColors = false;
            this.btnLogout.AutoRoundBorders = true;
            this.btnLogout.AutoSizeLeftIcon = true;
            this.btnLogout.AutoSizeRightIcon = true;
            this.btnLogout.BackColor = System.Drawing.Color.Transparent;
            this.btnLogout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnLogout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogout.BackgroundImage")));
            this.btnLogout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.ButtonText = "Log Out";
            this.btnLogout.ButtonTextMarginLeft = 0;
            this.btnLogout.ColorContrastOnClick = 45;
            this.btnLogout.ColorContrastOnHover = 45;
            this.btnLogout.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnLogout.CustomizableEdges = borderEdges3;
            this.btnLogout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogout.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLogout.ForeColor = System.Drawing.Color.White;
            this.btnLogout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogout.IconMarginLeft = 11;
            this.btnLogout.IconPadding = 2;
            this.btnLogout.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogout.IconSize = 25;
            this.btnLogout.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnLogout.IdleBorderRadius = 30;
            this.btnLogout.IdleBorderThickness = 1;
            this.btnLogout.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnLogout.IdleIconLeftImage = global::WPFinalPlease.Properties.Resources.icons8_logout_96;
            this.btnLogout.IdleIconRightImage = null;
            this.btnLogout.IndicateFocus = false;
            this.btnLogout.Location = new System.Drawing.Point(29, 39);
            this.btnLogout.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogout.OnDisabledState.BorderRadius = 1;
            this.btnLogout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnDisabledState.BorderThickness = 1;
            this.btnLogout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogout.OnDisabledState.IconLeftImage = null;
            this.btnLogout.OnDisabledState.IconRightImage = null;
            this.btnLogout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLogout.onHoverState.BorderRadius = 1;
            this.btnLogout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.onHoverState.BorderThickness = 1;
            this.btnLogout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLogout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.onHoverState.IconLeftImage = null;
            this.btnLogout.onHoverState.IconRightImage = null;
            this.btnLogout.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnLogout.OnIdleState.BorderRadius = 1;
            this.btnLogout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnIdleState.BorderThickness = 1;
            this.btnLogout.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(211)))), ((int)(((byte)(33)))));
            this.btnLogout.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.OnIdleState.IconLeftImage = global::WPFinalPlease.Properties.Resources.icons8_logout_96;
            this.btnLogout.OnIdleState.IconRightImage = null;
            this.btnLogout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLogout.OnPressedState.BorderRadius = 1;
            this.btnLogout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnPressedState.BorderThickness = 1;
            this.btnLogout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLogout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.OnPressedState.IconLeftImage = null;
            this.btnLogout.OnPressedState.IconRightImage = null;
            this.btnLogout.Size = new System.Drawing.Size(165, 32);
            this.btnLogout.TabIndex = 6;
            this.btnLogout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogout.TextMarginLeft = 0;
            this.btnLogout.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLogout.UseDefaultRadiusAndThickness = true;
            this.btnLogout.Click += new System.EventHandler(this.bunifuButton7_Click);
            // 
            // btnNotification
            // 
            this.btnNotification.AllowAnimations = true;
            this.btnNotification.AllowMouseEffects = true;
            this.btnNotification.AllowToggling = false;
            this.btnNotification.AnimationSpeed = 200;
            this.btnNotification.AutoGenerateColors = false;
            this.btnNotification.AutoRoundBorders = false;
            this.btnNotification.AutoSizeLeftIcon = true;
            this.btnNotification.AutoSizeRightIcon = true;
            this.btnNotification.BackColor = System.Drawing.Color.Transparent;
            this.btnNotification.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnNotification.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNotification.BackgroundImage")));
            this.btnNotification.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNotification.ButtonText = "Notification";
            this.btnNotification.ButtonTextMarginLeft = 0;
            this.btnNotification.ColorContrastOnClick = 45;
            this.btnNotification.ColorContrastOnHover = 45;
            this.btnNotification.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnNotification.CustomizableEdges = borderEdges4;
            this.btnNotification.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNotification.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNotification.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNotification.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNotification.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNotification.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNotification.ForeColor = System.Drawing.Color.Black;
            this.btnNotification.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNotification.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNotification.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNotification.IconMarginLeft = 11;
            this.btnNotification.IconPadding = 10;
            this.btnNotification.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNotification.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNotification.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNotification.IconSize = 25;
            this.btnNotification.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnNotification.IdleBorderRadius = 1;
            this.btnNotification.IdleBorderThickness = 1;
            this.btnNotification.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnNotification.IdleIconLeftImage = null;
            this.btnNotification.IdleIconRightImage = null;
            this.btnNotification.IndicateFocus = false;
            this.btnNotification.Location = new System.Drawing.Point(0, 362);
            this.btnNotification.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnNotification.Name = "btnNotification";
            this.btnNotification.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNotification.OnDisabledState.BorderRadius = 1;
            this.btnNotification.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNotification.OnDisabledState.BorderThickness = 1;
            this.btnNotification.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNotification.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNotification.OnDisabledState.IconLeftImage = null;
            this.btnNotification.OnDisabledState.IconRightImage = null;
            this.btnNotification.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnNotification.onHoverState.BorderRadius = 1;
            this.btnNotification.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNotification.onHoverState.BorderThickness = 1;
            this.btnNotification.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnNotification.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNotification.onHoverState.IconLeftImage = null;
            this.btnNotification.onHoverState.IconRightImage = null;
            this.btnNotification.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnNotification.OnIdleState.BorderRadius = 1;
            this.btnNotification.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNotification.OnIdleState.BorderThickness = 1;
            this.btnNotification.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnNotification.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnNotification.OnIdleState.IconLeftImage = null;
            this.btnNotification.OnIdleState.IconRightImage = null;
            this.btnNotification.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNotification.OnPressedState.BorderRadius = 1;
            this.btnNotification.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNotification.OnPressedState.BorderThickness = 1;
            this.btnNotification.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNotification.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNotification.OnPressedState.IconLeftImage = null;
            this.btnNotification.OnPressedState.IconRightImage = null;
            this.btnNotification.Size = new System.Drawing.Size(225, 41);
            this.btnNotification.TabIndex = 4;
            this.btnNotification.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNotification.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNotification.TextMarginLeft = 0;
            this.btnNotification.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNotification.UseDefaultRadiusAndThickness = true;
            // 
            // btnOngoingWork
            // 
            this.btnOngoingWork.AllowAnimations = true;
            this.btnOngoingWork.AllowMouseEffects = true;
            this.btnOngoingWork.AllowToggling = false;
            this.btnOngoingWork.AnimationSpeed = 200;
            this.btnOngoingWork.AutoGenerateColors = false;
            this.btnOngoingWork.AutoRoundBorders = false;
            this.btnOngoingWork.AutoSizeLeftIcon = true;
            this.btnOngoingWork.AutoSizeRightIcon = true;
            this.btnOngoingWork.BackColor = System.Drawing.Color.Transparent;
            this.btnOngoingWork.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnOngoingWork.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOngoingWork.BackgroundImage")));
            this.btnOngoingWork.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOngoingWork.ButtonText = "Ongoing Works";
            this.btnOngoingWork.ButtonTextMarginLeft = 0;
            this.btnOngoingWork.ColorContrastOnClick = 45;
            this.btnOngoingWork.ColorContrastOnHover = 45;
            this.btnOngoingWork.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnOngoingWork.CustomizableEdges = borderEdges5;
            this.btnOngoingWork.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOngoingWork.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOngoingWork.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOngoingWork.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOngoingWork.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOngoingWork.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOngoingWork.ForeColor = System.Drawing.Color.Black;
            this.btnOngoingWork.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOngoingWork.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOngoingWork.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOngoingWork.IconMarginLeft = 11;
            this.btnOngoingWork.IconPadding = 10;
            this.btnOngoingWork.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOngoingWork.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOngoingWork.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOngoingWork.IconSize = 25;
            this.btnOngoingWork.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnOngoingWork.IdleBorderRadius = 1;
            this.btnOngoingWork.IdleBorderThickness = 1;
            this.btnOngoingWork.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnOngoingWork.IdleIconLeftImage = null;
            this.btnOngoingWork.IdleIconRightImage = null;
            this.btnOngoingWork.IndicateFocus = false;
            this.btnOngoingWork.Location = new System.Drawing.Point(0, 314);
            this.btnOngoingWork.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnOngoingWork.Name = "btnOngoingWork";
            this.btnOngoingWork.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOngoingWork.OnDisabledState.BorderRadius = 1;
            this.btnOngoingWork.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOngoingWork.OnDisabledState.BorderThickness = 1;
            this.btnOngoingWork.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOngoingWork.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOngoingWork.OnDisabledState.IconLeftImage = null;
            this.btnOngoingWork.OnDisabledState.IconRightImage = null;
            this.btnOngoingWork.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnOngoingWork.onHoverState.BorderRadius = 1;
            this.btnOngoingWork.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOngoingWork.onHoverState.BorderThickness = 1;
            this.btnOngoingWork.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnOngoingWork.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOngoingWork.onHoverState.IconLeftImage = null;
            this.btnOngoingWork.onHoverState.IconRightImage = null;
            this.btnOngoingWork.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnOngoingWork.OnIdleState.BorderRadius = 1;
            this.btnOngoingWork.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOngoingWork.OnIdleState.BorderThickness = 1;
            this.btnOngoingWork.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnOngoingWork.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnOngoingWork.OnIdleState.IconLeftImage = null;
            this.btnOngoingWork.OnIdleState.IconRightImage = null;
            this.btnOngoingWork.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnOngoingWork.OnPressedState.BorderRadius = 1;
            this.btnOngoingWork.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOngoingWork.OnPressedState.BorderThickness = 1;
            this.btnOngoingWork.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnOngoingWork.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOngoingWork.OnPressedState.IconLeftImage = null;
            this.btnOngoingWork.OnPressedState.IconRightImage = null;
            this.btnOngoingWork.Size = new System.Drawing.Size(225, 41);
            this.btnOngoingWork.TabIndex = 3;
            this.btnOngoingWork.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOngoingWork.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOngoingWork.TextMarginLeft = 0;
            this.btnOngoingWork.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOngoingWork.UseDefaultRadiusAndThickness = true;
            // 
            // btnWorkerList
            // 
            this.btnWorkerList.AllowAnimations = true;
            this.btnWorkerList.AllowMouseEffects = true;
            this.btnWorkerList.AllowToggling = false;
            this.btnWorkerList.AnimationSpeed = 200;
            this.btnWorkerList.AutoGenerateColors = false;
            this.btnWorkerList.AutoRoundBorders = false;
            this.btnWorkerList.AutoSizeLeftIcon = true;
            this.btnWorkerList.AutoSizeRightIcon = true;
            this.btnWorkerList.BackColor = System.Drawing.Color.Transparent;
            this.btnWorkerList.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnWorkerList.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnWorkerList.BackgroundImage")));
            this.btnWorkerList.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWorkerList.ButtonText = "Worker List";
            this.btnWorkerList.ButtonTextMarginLeft = 0;
            this.btnWorkerList.ColorContrastOnClick = 45;
            this.btnWorkerList.ColorContrastOnHover = 45;
            this.btnWorkerList.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnWorkerList.CustomizableEdges = borderEdges6;
            this.btnWorkerList.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnWorkerList.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWorkerList.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnWorkerList.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnWorkerList.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnWorkerList.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnWorkerList.ForeColor = System.Drawing.Color.Black;
            this.btnWorkerList.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnWorkerList.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnWorkerList.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnWorkerList.IconMarginLeft = 11;
            this.btnWorkerList.IconPadding = 10;
            this.btnWorkerList.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnWorkerList.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnWorkerList.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnWorkerList.IconSize = 25;
            this.btnWorkerList.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnWorkerList.IdleBorderRadius = 1;
            this.btnWorkerList.IdleBorderThickness = 1;
            this.btnWorkerList.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnWorkerList.IdleIconLeftImage = null;
            this.btnWorkerList.IdleIconRightImage = null;
            this.btnWorkerList.IndicateFocus = false;
            this.btnWorkerList.Location = new System.Drawing.Point(0, 266);
            this.btnWorkerList.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnWorkerList.Name = "btnWorkerList";
            this.btnWorkerList.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWorkerList.OnDisabledState.BorderRadius = 1;
            this.btnWorkerList.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWorkerList.OnDisabledState.BorderThickness = 1;
            this.btnWorkerList.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnWorkerList.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnWorkerList.OnDisabledState.IconLeftImage = null;
            this.btnWorkerList.OnDisabledState.IconRightImage = null;
            this.btnWorkerList.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnWorkerList.onHoverState.BorderRadius = 1;
            this.btnWorkerList.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWorkerList.onHoverState.BorderThickness = 1;
            this.btnWorkerList.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnWorkerList.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnWorkerList.onHoverState.IconLeftImage = null;
            this.btnWorkerList.onHoverState.IconRightImage = null;
            this.btnWorkerList.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnWorkerList.OnIdleState.BorderRadius = 1;
            this.btnWorkerList.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWorkerList.OnIdleState.BorderThickness = 1;
            this.btnWorkerList.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnWorkerList.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnWorkerList.OnIdleState.IconLeftImage = null;
            this.btnWorkerList.OnIdleState.IconRightImage = null;
            this.btnWorkerList.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnWorkerList.OnPressedState.BorderRadius = 1;
            this.btnWorkerList.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWorkerList.OnPressedState.BorderThickness = 1;
            this.btnWorkerList.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnWorkerList.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnWorkerList.OnPressedState.IconLeftImage = null;
            this.btnWorkerList.OnPressedState.IconRightImage = null;
            this.btnWorkerList.Size = new System.Drawing.Size(225, 41);
            this.btnWorkerList.TabIndex = 2;
            this.btnWorkerList.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnWorkerList.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnWorkerList.TextMarginLeft = 0;
            this.btnWorkerList.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnWorkerList.UseDefaultRadiusAndThickness = true;
            // 
            // btnJobList
            // 
            this.btnJobList.AllowAnimations = true;
            this.btnJobList.AllowMouseEffects = true;
            this.btnJobList.AllowToggling = false;
            this.btnJobList.AnimationSpeed = 200;
            this.btnJobList.AutoGenerateColors = false;
            this.btnJobList.AutoRoundBorders = false;
            this.btnJobList.AutoSizeLeftIcon = true;
            this.btnJobList.AutoSizeRightIcon = true;
            this.btnJobList.BackColor = System.Drawing.Color.Transparent;
            this.btnJobList.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnJobList.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnJobList.BackgroundImage")));
            this.btnJobList.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJobList.ButtonText = "Job List";
            this.btnJobList.ButtonTextMarginLeft = 0;
            this.btnJobList.ColorContrastOnClick = 45;
            this.btnJobList.ColorContrastOnHover = 45;
            this.btnJobList.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnJobList.CustomizableEdges = borderEdges7;
            this.btnJobList.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnJobList.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJobList.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJobList.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJobList.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnJobList.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnJobList.ForeColor = System.Drawing.Color.Black;
            this.btnJobList.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnJobList.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnJobList.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnJobList.IconMarginLeft = 11;
            this.btnJobList.IconPadding = 10;
            this.btnJobList.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnJobList.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnJobList.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnJobList.IconSize = 25;
            this.btnJobList.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnJobList.IdleBorderRadius = 1;
            this.btnJobList.IdleBorderThickness = 1;
            this.btnJobList.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnJobList.IdleIconLeftImage = null;
            this.btnJobList.IdleIconRightImage = null;
            this.btnJobList.IndicateFocus = false;
            this.btnJobList.Location = new System.Drawing.Point(0, 219);
            this.btnJobList.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnJobList.Name = "btnJobList";
            this.btnJobList.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJobList.OnDisabledState.BorderRadius = 1;
            this.btnJobList.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJobList.OnDisabledState.BorderThickness = 1;
            this.btnJobList.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJobList.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJobList.OnDisabledState.IconLeftImage = null;
            this.btnJobList.OnDisabledState.IconRightImage = null;
            this.btnJobList.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnJobList.onHoverState.BorderRadius = 1;
            this.btnJobList.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJobList.onHoverState.BorderThickness = 1;
            this.btnJobList.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnJobList.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnJobList.onHoverState.IconLeftImage = null;
            this.btnJobList.onHoverState.IconRightImage = null;
            this.btnJobList.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnJobList.OnIdleState.BorderRadius = 1;
            this.btnJobList.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJobList.OnIdleState.BorderThickness = 1;
            this.btnJobList.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.btnJobList.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnJobList.OnIdleState.IconLeftImage = null;
            this.btnJobList.OnIdleState.IconRightImage = null;
            this.btnJobList.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnJobList.OnPressedState.BorderRadius = 1;
            this.btnJobList.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJobList.OnPressedState.BorderThickness = 1;
            this.btnJobList.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnJobList.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnJobList.OnPressedState.IconLeftImage = null;
            this.btnJobList.OnPressedState.IconRightImage = null;
            this.btnJobList.Size = new System.Drawing.Size(225, 41);
            this.btnJobList.TabIndex = 1;
            this.btnJobList.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnJobList.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnJobList.TextMarginLeft = 0;
            this.btnJobList.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnJobList.UseDefaultRadiusAndThickness = true;
            this.btnJobList.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // btnChangeAvatar
            // 
            this.btnChangeAvatar.AllowAnimations = true;
            this.btnChangeAvatar.AllowMouseEffects = true;
            this.btnChangeAvatar.AllowToggling = false;
            this.btnChangeAvatar.AnimationSpeed = 200;
            this.btnChangeAvatar.AutoGenerateColors = false;
            this.btnChangeAvatar.AutoRoundBorders = true;
            this.btnChangeAvatar.AutoSizeLeftIcon = true;
            this.btnChangeAvatar.AutoSizeRightIcon = true;
            this.btnChangeAvatar.BackColor = System.Drawing.Color.Transparent;
            this.btnChangeAvatar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(35)))), ((int)(((byte)(124)))));
            this.btnChangeAvatar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangeAvatar.BackgroundImage")));
            this.btnChangeAvatar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeAvatar.ButtonText = "Change Avatar";
            this.btnChangeAvatar.ButtonTextMarginLeft = 0;
            this.btnChangeAvatar.ColorContrastOnClick = 45;
            this.btnChangeAvatar.ColorContrastOnHover = 45;
            this.btnChangeAvatar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnChangeAvatar.CustomizableEdges = borderEdges8;
            this.btnChangeAvatar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangeAvatar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangeAvatar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangeAvatar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangeAvatar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangeAvatar.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.btnChangeAvatar.ForeColor = System.Drawing.Color.White;
            this.btnChangeAvatar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangeAvatar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeAvatar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChangeAvatar.IconMarginLeft = 11;
            this.btnChangeAvatar.IconPadding = 10;
            this.btnChangeAvatar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangeAvatar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeAvatar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChangeAvatar.IconSize = 25;
            this.btnChangeAvatar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(35)))), ((int)(((byte)(124)))));
            this.btnChangeAvatar.IdleBorderRadius = 30;
            this.btnChangeAvatar.IdleBorderThickness = 1;
            this.btnChangeAvatar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(35)))), ((int)(((byte)(124)))));
            this.btnChangeAvatar.IdleIconLeftImage = null;
            this.btnChangeAvatar.IdleIconRightImage = null;
            this.btnChangeAvatar.IndicateFocus = false;
            this.btnChangeAvatar.Location = new System.Drawing.Point(37, 161);
            this.btnChangeAvatar.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btnChangeAvatar.Name = "btnChangeAvatar";
            this.btnChangeAvatar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangeAvatar.OnDisabledState.BorderRadius = 1;
            this.btnChangeAvatar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeAvatar.OnDisabledState.BorderThickness = 1;
            this.btnChangeAvatar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangeAvatar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangeAvatar.OnDisabledState.IconLeftImage = null;
            this.btnChangeAvatar.OnDisabledState.IconRightImage = null;
            this.btnChangeAvatar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangeAvatar.onHoverState.BorderRadius = 1;
            this.btnChangeAvatar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeAvatar.onHoverState.BorderThickness = 1;
            this.btnChangeAvatar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangeAvatar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChangeAvatar.onHoverState.IconLeftImage = null;
            this.btnChangeAvatar.onHoverState.IconRightImage = null;
            this.btnChangeAvatar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(35)))), ((int)(((byte)(124)))));
            this.btnChangeAvatar.OnIdleState.BorderRadius = 1;
            this.btnChangeAvatar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeAvatar.OnIdleState.BorderThickness = 1;
            this.btnChangeAvatar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(35)))), ((int)(((byte)(124)))));
            this.btnChangeAvatar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChangeAvatar.OnIdleState.IconLeftImage = null;
            this.btnChangeAvatar.OnIdleState.IconRightImage = null;
            this.btnChangeAvatar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangeAvatar.OnPressedState.BorderRadius = 1;
            this.btnChangeAvatar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeAvatar.OnPressedState.BorderThickness = 1;
            this.btnChangeAvatar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangeAvatar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangeAvatar.OnPressedState.IconLeftImage = null;
            this.btnChangeAvatar.OnPressedState.IconRightImage = null;
            this.btnChangeAvatar.Size = new System.Drawing.Size(151, 32);
            this.btnChangeAvatar.TabIndex = 2;
            this.btnChangeAvatar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangeAvatar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangeAvatar.TextMarginLeft = 0;
            this.btnChangeAvatar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangeAvatar.UseDefaultRadiusAndThickness = true;
            // 
            // pBoxAvatar
            // 
            this.pBoxAvatar.Location = new System.Drawing.Point(75, 45);
            this.pBoxAvatar.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.pBoxAvatar.Name = "pBoxAvatar";
            this.pBoxAvatar.Size = new System.Drawing.Size(75, 81);
            this.pBoxAvatar.TabIndex = 0;
            this.pBoxAvatar.TabStop = false;
            // 
            // ucMainMenu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.btnAccountSetting);
            this.Controls.Add(this.bunifuPanel1);
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "ucMainMenu";
            this.Size = new System.Drawing.Size(960, 650);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pBoxAvatar)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        public System.Windows.Forms.PictureBox pBoxAvatar;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangeAvatar;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNotification;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOngoingWork;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnWorkerList;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnJobList;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAccountSetting;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTurnOff;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogout;
    }
}
